FROM tensorflow/tensorflow:2.16.2-gpu-jupyter

RUN apt-get update && apt-get -y install wget vim sudo
COPY shortcuts.sh /etc/profile.d/00-shortcuts.sh
RUN echo '\n. /etc/profile.d/00-shortcuts.sh' >> /etc/bash.bashrc

RUN git clone https://github.com/MIC-DKFZ/HD-BET /tmp/hd-bet && \
    pip install -e /tmp/hd-bet/

# Installing elastix
RUN wget https://github.com/SuperElastix/elastix/releases/download/5.0.0/elastix-5.0.0-Linux.tar.bz2 -P /tmp/ && \
    mkdir /opt/elastix-5.0.0-linux && \
    tar -xf /tmp/elastix-5.0.0-Linux.tar.bz2 -C /opt/elastix-5.0.0-linux && \
    rm /tmp/elastix-5.0.0-Linux.tar.bz2 && \
    chmod +x /opt/elastix-5.0.0-linux/bin/*

ENV ELASTIX_PATH=/opt/elastix-5.0.0-linux/bin/

# Install Ants
RUN wget https://github.com/ANTsX/ANTs/releases/download/v2.1.0/Linux_Ubuntu14.04.tar.bz2 -P /tmp/ && \
    mkdir /opt/ants-2.1.0 && \
    tar -xf /tmp/Linux_Ubuntu14.04.tar.bz2 -C /opt/ants-2.1.0 && \
    rm /tmp/Linux_Ubuntu14.04.tar.bz2 

ENV PATH="$PATH:/opt/ants-2.1.0/ANTs.2.1.0.Debian-Ubuntu_X64/"

# initialize ldconfig for non root users
RUN echo 'ALL ALL=(root) NOPASSWD: /usr/sbin/ldconfig' >> /etc/sudoers
# prepend the ldconfig line with sudo to run as root
RUN sed -i '/ldconfig/c\sudo ldconfig' /etc/bash.bashrc

RUN pip install tensorflow-probability[tf] && \
    pip install tensorflow[and-cuda]